// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://txvsgglsjrbufyifzwgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dnNnZ2xzanJidWZ5aWZ6d2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTkyOTcsImV4cCI6MjA1NTM5NTI5N30.UvC713nZk5ubDlXhme8cgzmgwvGMHUyO9FHoQETO5hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);